### ISSUE TITLE
"QXcbConnection: Could not connect to display" 

### ISSUE THREAD

**Issue by calufa** [YuvalNirkin/face_swap#1]
Hi, thanks for the code. 

I am having trouble running the code. I successfully compilee the project, but when I try to run `./face_swap_image --cfg test.cfg`, I get the following error:

`QXcbConnection: Could not connect to display`
`Aborted`

I am running the code inside a docker container.

**Comment by YuvalNirkin** [comment]
The face swap applications require an OpenGL context to work.
This is done using Qt offscreen rendering.

I have no way to test the application in the same environment you do but try to follow this post I think it might help: [http://stackoverflow.com/questions/25281992/alternatives-to-ssh-x11-forwarding-for-docker-containers/25334301#25334301](http://stackoverflow.com/questions/25281992/alternatives-to-ssh-x11-forwarding-for-docker-containers/25334301#25334301)

**Comment by sunjunlishi** [comment]
![bruce_willis_01](https://cloud.githubusercontent.com/assets/11845664/26525862/0275df4e-4397-11e7-89ce-97c4fe6b09b1.jpg)
![render](https://cloud.githubusercontent.com/assets/11845664/26525854/d791153c-4396-11e7-8cd3-f6b13ed6329a.jpg)
very cool ,i have got it

**Comment by YuvalNirkin** [comment]
Great! :)

**Comment by RudyChin** [comment]
@sunjunlishi that looks awesome.
Would you mind sharing your environment or any information regarding building the code up?
Mine one seems to have problem as mentioned in #3 
Thanks

**Comment by daili0015** [comment]
I ran it on docker too, met the same problem. Finally solved it by switching to [a  docker image](https://hub.docker.com/r/dorowu/ubuntu-desktop-lxde-vnc/) with desktop.
Now i successed:
![out](https://user-images.githubusercontent.com/24294293/28313443-6ebaca32-6be9-11e7-9826-07f40d6f48c9.jpg)
It's really cool ! From face detection、face segment、3D models to face swap, that's amazing works ！
——————————————————————————————————————
These are results on my docker container : 
Under these cases , it performs well : 
![qq 20170718190054](https://user-images.githubusercontent.com/24294293/28313992-86792590-6beb-11e7-8fc7-403f631582c1.png)

But the below groups seem abnormal:
Group 1:
![1](https://user-images.githubusercontent.com/24294293/28314021-9e1c7530-6beb-11e7-9b4f-38e0c169a63a.jpg)
![2](https://user-images.githubusercontent.com/24294293/28314022-9e1cb932-6beb-11e7-8702-1f05de03e9ef.jpg)
![out](https://user-images.githubusercontent.com/24294293/28314037-a241203e-6beb-11e7-9c18-5fb15b1bd0e6.jpg)
Group 2:
![1](https://user-images.githubusercontent.com/24294293/28314371-eb8ea29c-6bec-11e7-8f51-4093e34036a4.jpg)
![2](https://user-images.githubusercontent.com/24294293/28314372-eb8f3aa4-6bec-11e7-9dd8-bc9829adab20.jpg)
![out](https://user-images.githubusercontent.com/24294293/28314378-f162921e-6bec-11e7-83a7-356ff8fb5bb3.jpg)
Group 3 (profile):
![1](https://user-images.githubusercontent.com/24294293/28314180-19f054ce-6bec-11e7-8eee-2532e1de1253.jpg)
![2](https://user-images.githubusercontent.com/24294293/28314179-19e753ce-6bec-11e7-80c8-e05ac49ca104.jpg)
![out](https://user-images.githubusercontent.com/24294293/28314187-1f044f92-6bec-11e7-8575-4cb1606c6ec0.jpg)
Group 4(size between face and nose、eyes、mouth):
![1](https://user-images.githubusercontent.com/24294293/28314244-52d27c5e-6bec-11e7-8273-ae10e693da50.jpg)
![2](https://user-images.githubusercontent.com/24294293/28314245-52d3b97a-6bec-11e7-873c-a5c47db3cd30.jpg)
![out](https://user-images.githubusercontent.com/24294293/28314252-582e840e-6bec-11e7-8c57-d329049b3756.jpg)
——————————————————————————————————————
1、Noticing this [https://github.com/YuvalNirkin/face_swap/issues/3](url) , i don't know whether it could be caused by my no GPU environment and those're just errors occur. So could you please run these pictures on your machine to cheak it？

**Comment by YuvalNirkin** [comment]
Congratulation! You got it working!
The issue is related to the algorithm as I do get about the same results:
![demo_orig](https://user-images.githubusercontent.com/3984115/28316750-b975e6c8-6bcc-11e7-94a8-18b799c43a07.jpg)
This is a problem with the 3DMM fitting as you can see in the left debug image. It has issues with very high resolutions. Resizing the images can sometimes help:
![demo_reduced](https://user-images.githubusercontent.com/3984115/28316825-025f4852-6bcd-11e7-9df7-f2233f766c5a.jpg)

**Comment by akashgoyal** [comment]
Hi @YuvalNirkin 
I am running this project on an AWS instance. And getting
```
QXcbConnection: Could not connect to display 
Aborted (core dumped)
```

Any luck running it on cloud ?

Thanks
Akash

**Comment by YuvalNirkin** [comment]
Hi @akashgoyal 
I haven't tried running the project on a AWS instance but you can try one of the following solutions:
[https://aws.amazon.com/about-aws/whats-new/2017/10/amazon-ec2-elastic-gpus-now-support-opengl-4-0-and-available-in-two-additional-regions/](https://aws.amazon.com/about-aws/whats-new/2017/10/amazon-ec2-elastic-gpus-now-support-opengl-4-0-and-available-in-two-additional-regions/)

[https://comtechies.com/how-to-set-up-gui-on-amazon-ec2-ubuntu-server.html](https://comtechies.com/how-to-set-up-gui-on-amazon-ec2-ubuntu-server.html)

Please confirm if any of those work for you.

**Comment by akashgoyal** [comment]
Hi @YuvalNirkin 
I was trying https://comtechies.com/how-to-set-up-gui-on-amazon-ec2-ubuntu-server.html
And I am not able to proceed after step 2.

Is their a way to do this completely command line. Can you suggest on possible code changes ?

**Comment by YuvalNirkin** [comment]
You can replace the OpenGL renderer with a software renderer.

**Comment by tjusxh** [comment]
I sovlve the QxcbConnection Could not connect to display by install XManager and "export Display=:localhost:11.0” in ~/.bashrc

But After that I come across the following question.

QXcbConnection: Failed to initialize XRandr
Could not initialize GLX
Aborted (core dumped)
